-- Drop and recreate Users table (Example)

DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  join_date TIMESTAMP NOT NULL,
  rating INTEGER DEFAULT 0,
  username VARCHAR(255) NOT NULL,
  profile_image VARCHAR(255)
);

DROP TABLE IF EXISTS items CASCADE;
CREATE TABLE items (
  id SERIAL PRIMARY KEY NOT NULL,
  owner_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  description VARCHAR(255),
  price INTEGER NOT NULL,
  condition INTEGER NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  list_date TIMESTAMP NOT NULL,
  category VARCHAR(255) NOT NULL,
  city VARCHAR(255),
  province VARCHAR(255),
  postal_code VARCHAR(255),
  sold BOOLEAN NOT NULL DEFAULT FALSE,
  active BOOLEAN NOT NULL DEFAULT TRUE
);

DROP TABLE IF EXISTS user_reviews CASCADE;
CREATE TABLE user_reviews (
  id SERIAL PRIMARY KEY NOT NULL,
  seller_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  buyer_id INTEGER REFERENCES users(id),
  item_id INTEGER REFERENCES items(id),
  rating INTEGER NOT NULL,
  description TEXT,
  date_created TIMESTAMP NOT NULL
);

